ServerHTTPConfig:
  host: 8080
  port: 8080
  envipment:
    - ${SERVER_HTTP_CONFIG_HOST}
  
DatabaseConfig:
  host: mongodb
  port: 27017
  name: device_manager

KafkaConfig:
  brokers: kafka:9092
  group: "group"

LoggerConfig:
  encoding: json
  level: info
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: message
    levelKey: level
    timeKey: time
    timeEncoder: ISO8601
    levelEncoder: capital
    durationEncoder: string
    callerEncoder: short
