version: '3'
services:
  debug:
    build: 
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8083:8080"
      - "4040:4000"

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafka
    # environment:
    #  - MONGODB_URL=mongo://localhost:27017
    # networks:
    #   - my-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # networks:
    #   - my-network


  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=event-create

# networks:
#   my-network:
#     driver: bridge

