version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      # - kafka
    # environment:
    #  - MONGODB_URL=mongodb://mongo:27015/

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27010:27015
    # volumes:
    #   - mongodb:/data/db

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   restart: always
  #   ports:
  #     - 2181:2181

  # kafka:
  #   image: wurstmeister/kafka
  #   restart: always
  #   ports:
  #     - 9092:9092
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=kafka
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CREATE_TOPICS=event-create
