version: '3'
services:

  debug:
    container_name: Device-manager-debugger
    build: 
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8083:8080"
      - "4040:4000"
    environment:
      - SERVER_HTTP_CONFIG_HOST=""
    depends_on:
      - mongodb
      - kafka

  app:
    container_name: device-manager
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    environment:
      - SERVER_HTTP_CONFIG_HOST=""
    depends_on:
      - mongodb
      - kafka

  mongodb:
    container_name: mongodb
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    environment:
      - DATABASE_CONFIG_HOST=mongodb

  zookeeper:
    container_name: Zookeeper
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    container_name: Kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=device-create,device-update,device-delete,event-create
    depends_on:
      - zookeeper
