ServerHTTPConfig:
  host: localhost
  port: 8080
  
DatabaseConfig:
  host: localhost
  port: 27017
  name: device_manager

KafkaConfig:
  brokers: localhost:29092
  group: "group"

LoggerConfig:
  encoding: json
  level: info
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: message
    levelKey: level
    timeKey: time
    timeEncoder: ISO8601
    levelEncoder: capital
    durationEncoder: string
    # callerEncoder: short
    encoderTime: "iso8601" 
    # encodeDuration: string
    # encodeCaller: short

